language: ruby

script: bundle exec rake travis

matrix:
  fast_finish: true
  include:
   - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.0
      gemfile: Gemfile
    - rvm: 2.1.1
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
#      env: COVERAGE=true
    - rvm: 2.1.1
      gemfile: gemfiles/Gemfile-edge
     - rvm: jruby-head
      gemfile: Gemfile

  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-head

notifications:
  email:
    - matt.eldridge@us.ibm.com

before_install:
  - gem update --system #  todo: workaround for https://github.com/rubygems/rubygems/pull/763
